version: '2'
services:
  web:
    image: wordpress:4.6.1
    depends_on:
      - database
    links:
      - database
    environment:
      - WORDPRESS_DB_HOST=database
      - WORDPRESS_DB_USER=root
      - WORDPRESS_DB_PASSWORD=root
      - WORDPRESS_DB_NAME=wordpress
      - WORDPRESS_TABLE_PREFIX=rabbin_
    ports:
      - "80:80"
  database:
    image: mysql:5.7.16
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=user
      - MYSQL_PASSWORD=user
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - database
    links:
      - database
    environment:
      - PMA_HOST=database
      - PMA_USER=root
      - PMA_PASSWORD=root
    ports:
      - "81:80"
